-- Этот файл больше не содержит тестовых данных
-- Реалистичные данные генерируются скриптом generate_realistic_data.sql
-- Для генерации данных выполните: psql -U postgres -d coursework_db -f generate_realistic_data.sql
